drop table if exists account cascade ;
drop table if exists account_ownersphip cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
drop table if exists account cascade ;
drop table if exists account_ownersphip cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
drop table if exists account cascade ;
drop table if exists account_ownersphip cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
drop table if exists account cascade ;
drop table if exists account_ownersphip cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
alter table account_ownersphip drop foreign key FK260jtx2hlxpeirsnah1pk9yo4;
alter table account_ownersphip drop foreign key FKd3u9jtc2ilqkyl4l5jpe3juos;
alter table contact_details drop foreign key FKoquianu78jwseltspxwjfrdnq;
alter table operation drop foreign key FKloy20r01mn4truqqu460w3j9q;
drop table if exists account;
drop table if exists account_ownersphip;
drop table if exists contact_details;
drop table if exists customer;
drop table if exists devise;
drop table if exists operation;
drop table if exists account cascade ;
drop table if exists account_ownersphip cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
drop table if exists account cascade ;
drop table if exists account_ownersphip cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
drop table if exists account cascade ;
drop table if exists account_ownersphip cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
drop table if exists account cascade ;
drop table if exists account_ownership cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
drop table if exists account cascade ;
drop table if exists account_ownership cascade ;
drop table if exists contact_details cascade ;
drop table if exists customer cascade ;
drop table if exists devise cascade ;
drop table if exists operation cascade ;
